import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.rufonts.ru/css/krovavy" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Hachi+Maru+Pop&family=Tiny5&display=swap" rel="stylesheet" />
        <link rel="preload" href="/clicker_image/1/0.png" as="image" />
        <link rel="preload" href="/clicker_image/1/1.png" as="image" />
        <link rel="preload" href="/clicker_image/1/2.png" as="image" />
        <link rel="preload" href="/clicker_image/1/3.png" as="image" />
        <link rel="preload" href="/clicker_image/1/4.png" as="image" />
        <link rel="preload" href="/clicker_image/1/5.png" as="image" />
        <link rel="preload" href="/clicker_image/1/6.png" as="image" />
        <script src="https://telegram.org/js/telegram-web-app.js"></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
