import type { Metadata } from "next";

import Script from "next/script";


import { Hachi_Maru_Pop, Tiny5 } from "next/font/google";

const hachiMaruPop = Hachi_Maru_Pop({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-hachi-maru-pop",
});

const tiny5 = Tiny5({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-tiny5",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${hachiMaruPop.variable} ${tiny5.variable}`}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preload" href="/clicker_image/1/0.png" as="image" />
        <link rel="preload" href="/clicker_image/1/1.png" as="image" />
        <link rel="preload" href="/clicker_image/1/2.png" as="image" />
        <link rel="preload" href="/clicker_image/1/3.png" as="image" />
        <link rel="preload" href="/clicker_image/1/4.png" as="image" />
        <link rel="preload" href="/clicker_image/1/5.png" as="image" />
        <link rel="preload" href="/clicker_image/1/6.png" as="image" />
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
        />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}